### ISSUE TITLE
getting an error in fetching JSON

### ISSUE THREAD

**Issue by ArpitaGupta4086** [ArpitaGupta4086/COVIDCasesPlotMap#1]
getting the error - Unexpected Token < in JSON at Position 0.
Also there is something wrong with the fetch url.

**Comment by NikhilC2209** [comment]
Hey! @ArpitaGupta4086 I think the problem here is that you are trying to read a local JSON file using fetch api, while the parameter in fetch api expects a http/https url, so basically you cannot access your filesystem using fetch API without a server, you can easily workaround this problem by:

1) Serving the JSON file using Node.js or any other backend language
2) Find an online api that gives you the same data as in data.json For example:
```javascript
fetch('https://www.anapioficeandfire.com/api/books')
  .then(response => response.json())
  .then(data => console.log(data))
  .catch(error => console.log(error));
```

**Comment by ArpitaGupta4086** [comment]
Thanks! @NikhilC2209, But fetch("/data.json")  was working fine on my local machine even without creating any server.

**Comment by ArpitaGupta4086** [comment]
Thanks! @NikhilC2209 I understood
